#!/usr/bin/env python
"""Build demo-site/data.js from committed results/.

    python demo-site/build.py        # from the repo root

Renders exactly the committed deterministic benchmark (4/4), the recorded
live-LLM run (2/2), the per-task execution traces, and the real ToolRegistry
rejection messages captured in results/jail_attack_evidence.json.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RESULTS = ROOT / "results"


def load(name: str):
    return json.loads((RESULTS / name).read_text(encoding="utf-8"))


traces = {}
for path in sorted((RESULTS / "benchmark_traces").glob("*.json")):
    t = load(str(path.relative_to(RESULTS)))
    traces[t["task_id"]] = {
        "task_description": t.get("task_description", ""),
        "state": t.get("state"),
        "steps_used": t.get("steps_used"),
        "replans": t.get("replans"),
        "files_changed": t.get("files_changed", []),
        "test_results": t.get("test_results", []),
        "actions": t.get("actions", []),
        "observations": t.get("observations", []),
    }

data = {
    "benchmark": load("benchmark_results.json"),
    "llm_benchmark": load("llm_benchmark_results.json"),
    "traces": traces,
    "attacks": load("jail_attack_evidence.json"),
}

out = Path(__file__).resolve().parent / "data.js"
out.write_text(
    "// Generated by demo-site/build.py from committed results/ - do not hand-edit.\n"
    "window.DATA = " + json.dumps(data, indent=1) + ";\n",
    encoding="utf-8",
)
print(f"wrote {out} ({out.stat().st_size} bytes)")
